### PR TITLE
Swapping null equality check

### PR DESCRIPTION
**Pull request by derekpyne**

### CODE REVIEW

**Comment by cmerrick** [comment]
Hi @derekpyne, thanks for your contribution!

In order for us to evaluate and accept your PR, we ask that you [sign a contribution license agreement](https://stitch-cla-enforcer.herokuapp.com/). It's all electronic and will take just minutes.

**Comment by cmerrick** [comment]
You did it @derekpyne!

Thank you for signing the Singer Contribution License Agreement.

**Comment by cmerrick** [comment]
I interpret the original code as, "only allow null values if the schema says they can be null" - which is a reasonable assertion.  What problem is this supposed to fix?

**Comment by derekpyne** [comment]
Yes, your right, that seems reasonable. Think the core issue is that it is falling into this case for valid value. For instance, if Value=False with type_schema=boolean.

**Comment by derekpyne** [comment]
We made a change to look for none instead of truthy value. Needed to add a special case for None strings. We don't have any ground truth data to check this off of. Just trying to get the sync to finish with what looks like a good parse. Do you have any test data to check this on?

**Comment by cmerrick** [comment]
The `is None` comparison makes sense.  What motivated you to add the special case for strings?  If a field permits nulls and strings then I would expect its schema to be `"type": ["string", "null"]`

**Comment by derekpyne** [comment]
Seeing 
`{'push_address': '38D37F634B8372CA5B640F24AC7D412E4D0764BFB3A442CF789D9764F888BF3D', 'named_user_id': '8a72abc75d61f069015d6ac474ac6995', 'last_registration': '2017-07-22T14:48:45', 'tags': [], 'ios': {'quiettime': {'end': None, 'start': None}, 'tz': None, 'badge': 0}, 'alias': None, 'tag_groups': {'ua_opt_in': ['true'], 'timezone': ['America/Chicago'], 'ua_locale_language': ['en'], 'ua_ios_sdk_version': ['8.0.X'], 'ua_locale_country': ['US'], 'ua_background_enabled': ['true'], 'ua_ios_version': ['10.3.X'], 'ua_ios_model': ['iPhone9,2'], 'ua_ios_app_version': ['2.0.28'], 'ua_location_enabled': ['false']}, 'opt_in': True, 'installed': True, 'created': '2017-07-22T14:47:28', 'device_type': 'ios', 'channel_id': '000ebe4e-326b-45bc-a579-7cada287c2b3', 'background': True}` as an entry which has a value of None in quiettime. Should be a more elegant way of handling this then the special case for string. Let me see if changing the schemas produces

**Comment by derekpyne** [comment]
Simplifying things by removing the special string case. Seems that the Urban Airship API is returning a large amount of `nulls` for fields/schemas that do not allow this. Will follow up after this pull request with a way to address that.

**Pull request merged**
